### ISSUE TITLE
which Cypress Version is supported by this plugin?

### ISSUE THREAD

**Issue by LiZhang19817** [reportportal/agent-js-cypress#115]
Hi Guys,

Want to confirm which Cypress Version is supported by this plugin?

Thanks
Luffy Zhang

**Comment by CassenH** [comment]
I've been using this for a while now in my CICD pipeline. It works like a charm for 9.X 

Since Cypress 10 just came out, I tried updating one of my projects to 10.0.3 today. Unfortunately this did not work out of the box using this plugin. I documented the error I'm getting [here](https://github.com/reportportal/agent-js-cypress/issues/116). For now I will stay on version 9.7 in all of my projects.

**Comment by SergFedosov** [comment]
Hi guys, 
does 5.0.4 version is supporting cypress 10.3.1? When **agent-js-cypress** will be supporting cypress 10 ?

**Comment by AmsterGet** [comment]
Hello @SergFedosov !
We plan to release support of Cypress 10.x in agent's 5.1.0 release. The approximate ETA is one-two weeks.

**Comment by rajaspar** [comment]
> Hello @SergFedosov ! We plan to release support of Cypress 10.x in agent's 5.1.0 release. The approximate ETA is one-two weeks.

Hello @AmsterGet Is there an update on this release? 

We upgraded to Cypress 10x a while ago and we've been unable to publish the results onto the report portal. Unfortunately, we don't have an option to downgrade the Cypress version.

**Comment by AmsterGet** [comment]
Hello @rajaspar and guys!
Sorry, I was on a long vacation and the fix was delayed.
We plan to publish the requested version soon (in 1-2 days). Now the release process is in progress.
As a temporary workaround you can use approach mentioned in [this issue comment](https://github.com/reportportal/agent-js-cypress/issues/116#issuecomment-1236834177).
Stay tuned.

**Comment by AmsterGet** [comment]
The version 5.1.0 released with Cypress 10.x support. Please [try it](https://www.npmjs.com/package/@reportportal/agent-js-cypress).
Thanks to @orgads and @dwentland24 for contribution!
