### ISSUE TITLE
Fail to merge reports

### ISSUE THREAD

**Issue by diogogt** [reportportal/agent-js-cypress#45]
Hello, 
I'm using the **agent-js-cypress**  from master and I have error on **reportportal-client**.

The **agent-js-cypress** send the _launches_ like String but the API wait _Long value_ :

The **agent-js-cypress**  send 
`{
  description: 'Merged launch',
  endTime: 1591208166778,
  extendSuitesDescription: true,
  launches: [ '3bb36bf8', '07e2f9ad', '27de20d4', '56da7005' ],
  mergeType: 'BASIC',
  mode: 'DEFAULT',
  name: 'E2E_Cypress',
  attributes: undefined
}`
Error: 
`
(node:24028) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. Invalid JSON input: Cannot deserialize value of type `java.lang.Long` from String \"3bb36bf8\": not a valid Long value; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String \"3bb36bf8\": not a valid Long value\n at [Source: (PushbackInputStream); line: 1, column: 99] (through reference chain: com.epam.ta.reportportal.ws.model.launch.MergeLaunchesRQ[\"launches\"]->java.util.HashSet[0])"}
    at ...\node_modules\reportportal-client\lib\rest.js:28:23`

Can you help me?

**Comment by paulmwhite** [comment]
I’m seeing this same issue

**Comment by vishallanke** [comment]
I am seeing same issue. Along with one major observation that from Git when I trigger pipelines, failed test cases gets stuck for a day and never gets updated inside RP

**Comment by ElenaRomanchuk** [comment]
Hi!
We released the new version of cypress reporter as a new package `@reportportal/agent-js-cypress`: https://www.npmjs.com/package/@reportportal/agent-js-cypress. It has a new possibility of runtime merge launches into single: https://github.com/reportportal/agent-js-cypress#automatically-merge-launches. You can try it now.
Also, merge launches with 'isLaunchMergeRequired' option will be fixed in nearest future in 5.0.1 version.
Please, let us know if this solves your issue.

**Comment by ElenaRomanchuk** [comment]
Will be fixed in scope of #54

**Comment by diogogt** [comment]
I test with the latest version **5.0.1** and it's work, thanks.
